server:
  port: 8080
spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-195-252-243.eu-west-1.compute.amazonaws.com:5432/d41uucs6kv315f
    username: zmwmnplpupimng
    password: 340bd38bb6ed38b35f16a0a51dc2cc4f54460aa254e7c098dfbf8dd6c5a16dd6
#for Security
uploadfile:
  app:
    jwtSecret: verySecretKey
    jwtExpiration: 86400

